/// Auto-generated by build/package-app.sh — DO NOT EDIT BY HAND, overwritten on every real
/// packaging run (and restored to the checked-in placeholder afterward). SHA-256 tree hash of
/// Contents/Resources/cli-src/ exactly as staged for this build.
public enum GeneratedCLIManifest {
    public static let expectedTreeHashHex = "UNSET-PLACEHOLDER-REGENERATE-VIA-build-package-app-sh"
}
