#!/bin/bash
# install.sh — 2-install-sh (PLAN.md §6, L4, L7, L10).
#
# Installs the CLI + vendored binaries from this repo tree into a stable prefix.
# Refuses non-arm64 (L7). Strips com.apple.quarantine on every copied binary. Verifies
# anylinuxfs's ad-hoc signature before enabling it (build-all.sh already `codesign -s -`
# signs anylinuxfs; gvproxy/vmnet-helper/vmproxy get formally signed by 2-signing, the
# next unit — not duplicated here). NTFSMAC_REPO defaults to khr898/ntfsmac (L10 — the
# repo owner placeholder must never appear literally in this file).
set -uo pipefail

NTFSMAC_REPO="${NTFSMAC_REPO:-khr898/ntfsmac}"
REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
PREFIX="${NTFSMAC_PREFIX:-/usr/local/ntfsmac}"
# Already-on-PATH convenience symlink (`ntfsmac` works with zero manual PATH setup) — a plain
# dir, never a shell-rc edit, so it works in every new shell immediately, unlike appending to
# .zshrc/.bash_profile which only takes effect after a reload and guesses at the user's shell.
PATH_SYMLINK="${NTFSMAC_PATH_SYMLINK:-/usr/local/bin/ntfsmac}"

refuse_non_arm64() {
  local arch
  arch="$(uname -m)"
  if [[ "$arch" != "arm64" ]]; then
    echo "install.sh: HARD-STOP — ntfsmac requires Apple Silicon (arm64), detected '$arch' (L7)" >&2
    return 1
  fi
}

verify_signature() {
  local bin="$1"
  if ! codesign -v "$bin" >/dev/null 2>&1; then
    echo "install.sh: HARD-STOP — $bin failed signature verification, refusing to enable" >&2
    return 1
  fi
}

strip_quarantine() {
  xattr -d com.apple.quarantine "$1" >/dev/null 2>&1 || true
}

install_binaries() {
  mkdir -p "$PREFIX/bin" "$PREFIX/libexec"

  cp "$REPO_ROOT/vendor/bin/anylinuxfs" "$PREFIX/bin/anylinuxfs" || return 1
  chmod +x "$PREFIX/bin/anylinuxfs" || return 1
  strip_quarantine "$PREFIX/bin/anylinuxfs"
  verify_signature "$PREFIX/bin/anylinuxfs" || return 1

  local bin
  for bin in gvproxy vmnet-helper vmproxy init-rootfs; do
    [[ -f "$REPO_ROOT/vendor/bin/$bin" ]] || continue
    cp "$REPO_ROOT/vendor/bin/$bin" "$PREFIX/libexec/$bin" || return 1
    chmod +x "$PREFIX/libexec/$bin" || return 1
    strip_quarantine "$PREFIX/libexec/$bin"
  done

  local kf
  for kf in Image Image-4K; do
    if [[ -f "$REPO_ROOT/vendor/kernel/$kf" ]]; then
      cp "$REPO_ROOT/vendor/kernel/$kf" "$PREFIX/libexec/$kf" || return 1
    fi
  done

  # modules.squashfs goes in $PREFIX/lib, not $PREFIX/libexec: init-rootfs's own
  # copyLinuxModules() reads it from prefixDir/lib/modules.squashfs (real path, read
  # from vendor/src/anylinuxfs/init-rootfs/main.go — confirmed the only consumer).
  if [[ -f "$REPO_ROOT/vendor/kernel/modules.squashfs" ]]; then
    mkdir -p "$PREFIX/lib"
    cp "$REPO_ROOT/vendor/kernel/modules.squashfs" "$PREFIX/lib/modules.squashfs" || return 1
  fi
}

install_cli() {
  mkdir -p "$PREFIX/libexec/ntfsmac/commands" "$PREFIX/libexec/ntfsmac/lib"
  cp "$REPO_ROOT"/cli/commands/*.sh "$PREFIX/libexec/ntfsmac/commands/" || return 1
  cp "$REPO_ROOT"/cli/lib/*.sh "$PREFIX/libexec/ntfsmac/lib/" || return 1
  chmod +x "$PREFIX"/libexec/ntfsmac/commands/*.sh || return 1
  local f
  for f in "$PREFIX"/libexec/ntfsmac/commands/*.sh "$PREFIX"/libexec/ntfsmac/lib/*.sh; do
    strip_quarantine "$f"
  done

  cat > "$PREFIX/bin/ntfsmac" <<DISPATCH
#!/bin/bash
# Generated by install.sh — dispatches to \$PREFIX/libexec/ntfsmac/commands/*.sh.
set -u
LIBEXEC="$PREFIX/libexec/ntfsmac"

print_help() {
  cat <<'HELP'
usage: ntfsmac <command> [args...]

commands:
  mount [device] [mount_point]       Mount an NTFS drive (omit device to pick from a list).
                                      Flags: --fs-driver ntfs-3g|ntfs3, --read-only
  unmount [device|mount_point]       Unmount a drive (omit to pick from active mounts)
  diagnose [--json]                  Read-only health check
  uninstall [--force] [--keep-cache] Remove the CLI, vendored deps, and the GUI helper
  help                               Show this message

'ntfsmac uninstall --help' shows uninstall's flags in detail.
HELP
}

sub="\${1:-}"
[[ \$# -gt 0 ]] && shift
case "\$sub" in
  mount) exec "\$LIBEXEC/commands/mount.sh" "\$@" ;;
  unmount) exec "\$LIBEXEC/commands/unmount.sh" "\$@" ;;
  diagnose) exec "\$LIBEXEC/commands/diagnose.sh" "\$@" ;;
  uninstall) exec "\$LIBEXEC/commands/uninstall.sh" "\$@" ;;
  help | --help | -h | "") print_help; exit 0 ;;
  *) echo "ntfsmac: unknown command '\$sub'" >&2; print_help >&2; exit 1 ;;
esac
DISPATCH
  chmod +x "$PREFIX/bin/ntfsmac" || return 1
  strip_quarantine "$PREFIX/bin/ntfsmac"
}

link_into_path() {
  local symlink_dir
  symlink_dir="$(dirname "$PATH_SYMLINK")"
  mkdir -p "$symlink_dir" 2>/dev/null
  if ln -sf "$PREFIX/bin/ntfsmac" "$PATH_SYMLINK" 2>/dev/null; then
    echo "install.sh: linked $PATH_SYMLINK -> $PREFIX/bin/ntfsmac (already on PATH)"
  else
    echo "install.sh: WARN — could not create $PATH_SYMLINK, add $PREFIX/bin to PATH manually" >&2
  fi
}

main() {
  # Self-elevate only if actually needed — mirrors mount.sh/uninstall.sh's own pattern, but
  # gated on real writability so a machine where $PREFIX/$PATH_SYMLINK's parent is already
  # user-writable (common: a prior Homebrew install commonly chowns /usr/local) never gets a
  # needless password prompt, and so the test suite (which always points both at a scratch
  # dir) never triggers it either.
  if [[ "${NTFSMAC_SKIP_ROOT_CHECK:-}" != "1" && $EUID -ne 0 ]]; then
    local prefix_parent symlink_parent needs_root=""
    prefix_parent="$(dirname "$PREFIX")"
    [[ -w "$PREFIX" || ( ! -e "$PREFIX" && -w "$prefix_parent" ) ]] || needs_root=1
    symlink_parent="$(dirname "$PATH_SYMLINK")"
    [[ -w "$symlink_parent" || ! -e "$symlink_parent" ]] || needs_root=1
    [[ -n "$needs_root" ]] && exec sudo "$0" "$@"
  fi

  # `--no-path-link`: the GUI's privileged helper runs this same script (already root, via
  # `HelperService.stageCLI`) to stage the CLI in the background on first helper install — per
  # explicit product decision, a GUI-only install must not expose `ntfsmac` on a Terminal PATH
  # the user never asked for. Standalone/tap installs (no flag) keep the symlink unchanged.
  local skip_link=""
  local arg
  for arg in "$@"; do
    [[ "$arg" == "--no-path-link" ]] && skip_link=1
  done

  refuse_non_arm64 || exit 1
  install_binaries || exit 1
  install_cli || exit 1
  [[ -z "$skip_link" ]] && link_into_path
  echo "install.sh: installed to $PREFIX (NTFSMAC_REPO=$NTFSMAC_REPO)"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi
